import type { JourneyEntry } from '@retry/protocol';
import { formatWhen } from '../../../lib/when.js';

// Build Journey (FR-ROOM-17). Entries are generated by the server from things
// that actually happened — room creation, a Blueprint question answered for
// the first time, a stage change, this week's Done count. Nobody can write one
// by hand, which is what makes it worth reading months later.

const MARK: Record<JourneyEntry['kind'], string> = {
  room_created: '◆',
  blueprint_first_edit: '✎',
  stage_change: '▸',
  weekly_done: '✓',
};

export function JourneyTimeline({ entries }: { entries: JourneyEntry[] }) {
  if (entries.length === 0) {
    return (
      <section className="flex flex-col gap-2">
        <h3 className="font-mono text-[11px] uppercase text-ink-muted">Build journey</h3>
        <p className="rounded-panel border border-edge bg-surface px-4 py-4 text-sm text-ink-muted">
          Nothing yet. Answer a blueprint question or move the project stage and it shows up here.
        </p>
      </section>
    );
  }

  // Newest first: the last thing that happened is the thing you came to see.
  const ordered = [...entries].sort((a, b) => b.createdAt.localeCompare(a.createdAt));

  return (
    <section className="flex flex-col gap-2">
      <h3 className="font-mono text-[11px] uppercase text-ink-muted">Build journey</h3>
      <ol className="flex flex-col rounded-panel border border-edge bg-surface">
        {ordered.map((entry) => (
          <li
            key={entry.id}
            className="flex gap-3 border-b border-edge px-4 py-2.5 last:border-b-0"
          >
            <span aria-hidden className="font-mono text-sm text-accent">
              {MARK[entry.kind]}
            </span>
            <div className="min-w-0">
              <p className="break-words text-sm text-ink">{entry.body}</p>
              <p className="font-mono text-[11px] text-ink-muted">{formatWhen(entry.createdAt)}</p>
            </div>
          </li>
        ))}
      </ol>
    </section>
  );
}
