import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TILE, OUT_DIR } from '../assets.config.js';

// Generates the Tiled editor project so the maps can be opened and refined by
// hand (docs/authoring-maps.md).
//
//   pnpm --filter @retry/maps tiled
//
// Two things get written into generated/tiled/ (gitignored, like everything
// pack-derived):
//
//   *.tsx                 one external tileset per sheet the build produced
//   retry.tiled-project   the project file you open in Tiled
//
// IMPORTANT: our map JSON EMBEDS its tilesets rather than referencing these
// .tsx files, because Phaser's Tiled parser cannot follow an external tileset
// reference — it would silently render nothing. The .tsx files exist so Tiled
// itself has named, browsable tilesets in its palette; when you save a map,
// keep Tiled's "Embed tilesets" behaviour (Map ▸ Properties, or just don't
// convert the embedded ones), and `pnpm validate` will catch it if you don't.

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const outDir = resolve(root, OUT_DIR, 'tiled');

type ManifestSheet = { key: string; file: string; width: number; height: number; columns: number; rows: number };
const manifest = JSON.parse(readFileSync(resolve(root, OUT_DIR, 'manifest.json'), 'utf8')) as {
  source: string;
  tilesets: ManifestSheet[];
};
if (manifest.source !== 'limezu') {
  throw new Error('the Tiled project needs the licensed pack built — run: pnpm assets:build');
}

mkdirSync(outDir, { recursive: true });

for (const sheet of manifest.tilesets) {
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- GENERATED by scripts/build-tiled.ts — do not edit, do not commit. -->',
    `<tileset version="1.10" tiledversion="1.11.0" name="${sheet.key}" tilewidth="${TILE}" tileheight="${TILE}" tilecount="${sheet.columns * sheet.rows}" columns="${sheet.columns}">`,
    // ../../tilesets/x.png — from generated/tiled/ back to generated/tilesets/.
    ` <image source="../${sheet.file}" width="${sheet.width}" height="${sheet.height}"/>`,
    '</tileset>',
    '',
  ].join('\n');
  writeFileSync(resolve(outDir, `${sheet.key}.tsx`), xml);
}

// Tiled resolves paths in a project relative to the project file. Pointing it
// at the repo's maps/ directory means File ▸ Open lands in the right place.
const project = {
  automappingRulesFile: '',
  commands: [],
  compatibilityVersion: 1100,
  extensionsPath: 'extensions',
  folders: ['../../maps', '.'],
  properties: [],
  propertyTypes: [],
};
writeFileSync(
  resolve(outDir, 'retry.tiled-project'),
  `${JSON.stringify(project, null, 4)}\n`,
);

console.log(`tiled: ${manifest.tilesets.length} tilesets + project → packages/maps/${OUT_DIR}/tiled/`);
console.log(`  open packages/maps/${OUT_DIR}/tiled/retry.tiled-project in Tiled`);
